# Copyright 2018 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: defaulting.webhook.tekton-pipelines.custom.tekton.dev
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-code-engine
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: tekton-code-engine-webhook
      namespace: tekton-code-engine
  failurePolicy: Fail
  sideEffects: None
  name: defaulting.webhook.tekton-pipelines.custom.tekton.dev
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.tekton-pipelines.custom.tekton.dev
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-code-engine
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: tekton-code-engine-webhook
      namespace: tekton-code-engine
  failurePolicy: Fail
  sideEffects: None
  name: validation.webhook.tekton-pipelines.custom.tekton.dev
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: config.webhook.tekton-pipelines.custom.tekton.dev
  labels:
    serving.knative.dev/release: devel
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-code-engine
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: tekton-code-engine-webhook
      namespace: tekton-code-engine
  failurePolicy: Fail
  sideEffects: None
  name: config.webhook.tekton-pipelines.custom.tekton.dev
#  namespaceSelector:
#    matchExpressions:
#    - key: custom.tekton.dev/release
#      operator: Exists
  objectSelector:
    matchLabels:
      app.kubernetes.io/part-of: tekton-code-engine
---
apiVersion: v1
kind: Secret
metadata:
  name: tekton-code-engine-webhook-certs
  namespace: tekton-code-engine
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-code-engine
# The data is populated at install time.
