---
apiVersion: custom.tekton.dev/v1alpha1
kind: CodeEngineTask
metadata:
  name: codeenginetask-1
spec:
  jobName: job-hello-world
---
apiVersion: custom.tekton.dev/v1alpha1
kind: CodeEngineTask
metadata:
  name: codeenginetask-2
spec:
  jobName: job-hello-world
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: codeenginetask-pipeline-cx2
spec:
  tasks:
    - name: run-custom-task-1
      taskRef:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: CodeEngineTask
        name: codeenginetask-1
    - name: run-custom-task-2
      taskRef:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: CodeEngineTask
        name: codeenginetask-2
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: codeenginetask-pipeline-run-cx2-001
spec:
  pipelineRef:
    name: codeenginetask-pipeline-cx2
