kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: finally-
spec:
  serviceAccountName: 'default'
  pipelineSpec:
    tasks:
      - name: task1 # successful task
        taskSpec:
          steps:
            - image: alpine:3.6
              name: hello
              script: |
                sleep 600
    finally:
      - name: task3 # this task verifies the status of dag tasks, it fails if verification fails
        taskSpec:
          steps:
            - image: alpine:3.6
              name: verify-dag-task-status
              script: |
                echo "i'm the finally"
                sleep 60