/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	codeenginetaskv1alpha1 "github.com/rafalbigaj/tekton-code-engine/pkg/apis/codeenginetask/v1alpha1"
	versioned "github.com/rafalbigaj/tekton-code-engine/pkg/client/clientset/versioned"
	internalinterfaces "github.com/rafalbigaj/tekton-code-engine/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/rafalbigaj/tekton-code-engine/pkg/client/listers/codeenginetask/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CodeEngineTaskInformer provides access to a shared informer and lister for
// CodeEngineTasks.
type CodeEngineTaskInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CodeEngineTaskLister
}

type codeEngineTaskInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCodeEngineTaskInformer constructs a new informer for CodeEngineTask type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCodeEngineTaskInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCodeEngineTaskInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCodeEngineTaskInformer constructs a new informer for CodeEngineTask type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCodeEngineTaskInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CustomV1alpha1().CodeEngineTasks(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CustomV1alpha1().CodeEngineTasks(namespace).Watch(context.TODO(), options)
			},
		},
		&codeenginetaskv1alpha1.CodeEngineTask{},
		resyncPeriod,
		indexers,
	)
}

func (f *codeEngineTaskInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCodeEngineTaskInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *codeEngineTaskInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&codeenginetaskv1alpha1.CodeEngineTask{}, f.defaultInformer)
}

func (f *codeEngineTaskInformer) Lister() v1alpha1.CodeEngineTaskLister {
	return v1alpha1.NewCodeEngineTaskLister(f.Informer().GetIndexer())
}
